BBS/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('web.urls', 'web'))),
    path('ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class UserInfo(models.Model):
    """用户表"""
    POWER_CHOICES = (
        (1, "普通用户"),
        (2, "版务"),
        (3, "版主"),
        (4, "管理员"),
    )

    username = models.CharField(verbose_name='用户名', max_length=32, db_index=True)
    email = models.EmailField(verbose_name='邮件', max_length=32)
    mobile_phone = models.CharField(verbose_name='手机号', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)
    head_portrait = models.ImageField(verbose_name='头像', null=True, upload_to='headPortrait/')
    power = models.SmallIntegerField(choices=POWER_CHOICES, default=1)
    power_name = models.CharField(max_length=20, default='普通用户')
    describe = models.TextField(verbose_name='个性签名', null=True)
    is_active = models.SmallIntegerField(default=1)
    is_staff = models.SmallIntegerField(default=1)

    def __str__(self):
        return self.username

class Forum(models.Model):
    """版块表"""
    forum_name = models.CharField(verbose_name='版块名', max_length=32, db_index=True)
    topic_count = models.IntegerField(default=0)
    concern_count = models.IntegerField(default=0)
    date_added = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    moderator = models.ForeignKey(UserInfo, null=True, on_delete=models.SET_NULL)
    picture = models.ImageField(verbose_name='图片', upload_to='picture/')
    background = models.ImageField(verbose_name='背景图片', upload_to='background/')

    def __str__(self):
        return self.forum_name

class ApplyforForum(models.Model):
    """申请创建版块表"""
    forum_name = models.CharField(verbose_name='版块名', max_length=32, db_index=True)
    picture = models.ImageField(verbose_name='图片', upload_to='picture/')
    background = models.ImageField(verbose_name='背景图片', upload_to='background/')
    date_added = models.DateTimeField(verbose_name='申请时间', auto_now_add=True)
    text = models.TextField(verbose_name='申请理由')
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

class Topic(models.Model):
    """帖子主题表"""
    topic_text = models.CharField(verbose_name='帖子内容', max_length=200)
    forum = models.ForeignKey(Forum,verbose_name='所属版块', on_delete=models.CASCADE)
    owner = models.ForeignKey(UserInfo, verbose_name='创建用户', on_delete=models.CASCADE)
    floor_count = models.IntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add=True)
    top = models.BooleanField(verbose_name='是否置顶', default=False)
    refined = models.BooleanField(verbose_name='是否加精', default=False)

    def __str__(self):
        if len(self.topic_text) > 36:
            return self.topic_text[:36] + '...'
        return self.topic_text[:36]

class Floor(models.Model):
    """回复楼层表"""
    floor_text = RichTextUploadingField()
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    owner = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    floor_number = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    great = models.IntegerField(default=0)

    def __str__(self):
        if len(self.floor_text) > 199:
            return self.floor_text[:199] + '...'
        return self.floor_text[:199]

class Comment(models.Model):
    """帖子评论表"""
    text = RichTextField()
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE)
    owner = models.ForeignKey(UserInfo, related_name="comments", on_delete=models.DO_NOTHING)
    by_owner = models.ForeignKey(UserInfo, null=True, related_name="replies", on_delete=models.DO_NOTHING)
    date_added = models.DateTimeField(auto_now_add=True)
    great = models.IntegerField(default=0)

    def __str__(self):
        return self.text

class UserToForum(models.Model):
    """用户关注模块表"""
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)

class Collect(models.Model):
    """用户收藏帖子表"""
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)

class ForumPower(models.Model):
    """版块权限表"""
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    forum = models.ForeignKey(Forum, null=True, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)

class FloorGreat(models.Model):
    """楼层点赞表"""
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)

class CommentGreat(models.Model):
    """回复点赞表"""
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)

class Inform_Floor(models.Model):
    """楼层举报表"""
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    floor = models.ForeignKey(Floor, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    status = models.BooleanField(default=False)

class UserToUser(models.Model):
    """用户关注用户表"""
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    by_owner = models.ForeignKey(UserInfo, null=True, related_name="br", on_delete=models.DO_NOTHING)
    status = models.BooleanField(default=True)

web/views/account.py
from django.shortcuts import render, redirect
from web.form.account import RegisterModelForm, SendSmsForm, LoginSMSForm, LoginForm
from web.form.account import HeadForm, PasswordForm, AccountForm
from django.http import HttpResponse, JsonResponse
from web import models
from django.db.models import Q
import datetime



def register(request):
    """注册"""
    if request.method == 'GET':
        form = RegisterModelForm()
        context = {'form': form}
        return render(request, 'web/register.html', context)

    form = RegisterModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        #注册完成直接登录
        username = form.cleaned_data['username']
        user_obj = models.UserInfo.objects.get(username=username)
        request.session['user_id'] = user_obj.id
        request.session.set_expiry(60 * 60 * 24 * 14)
        return JsonResponse({'status': True, 'data': '/'})
    return JsonResponse({'status': False, 'error': form.errors})

def send_sms(request):
    """发送短信"""
    form = SendSmsForm(request, data=request.GET)
    print('选择')
    if form.is_valid():
        return JsonResponse({'status': True})
    print('成功')
    return JsonResponse({'status': False, 'error': form.errors})

def login_sms(request):
    """短信登录"""
    if request.method == 'GET':
        form = LoginSMSForm()
        context = {'form': form}
        return render(request, 'web/login_sms.html', context)
    form = LoginSMSForm(request.POST)
    if form.is_valid():
        #用户输入正确， 登录成功
        mobile_phone = form.cleaned_data['mobile_phone']
        #把用户名写入到session中
        user_object = models.UserInfo.objects.get(mobile_phone=mobile_phone)
        request.session['user_id'] = user_object.id
        request.session.set_expiry(60 * 60 * 24 * 14)
        return JsonResponse({"status": True, 'data': "/"})
    return JsonResponse({"status": False, "error": form.errors})

def login(request):
    """用户名和密码登录"""
    form = LoginForm(request)
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user_obj = models.UserInfo.objects.filter(
                Q(email=username)|Q(mobile_phone=username)).filter(
                password=password).first()
            if user_obj:
                #登录成功
                request.session['user_id'] = user_obj.id
                request.session.set_expiry(60 * 60 * 24 * 14)
                return redirect('web:home')
            form.add_error('username', '用户名或密码错误')
    context = {'form': form}

    return render(request, 'web/login.html', context)

def image_code(request):
    """生成图片验证码"""
    from io import BytesIO
    from utils.image_code import check_code

    image_object, code = check_code()

    request.session['image_code'] = code
    request.session.set_expiry(60)

    stream = BytesIO()
    image_object.save(stream, 'png')
    return HttpResponse(stream.getvalue())

def logout(request):
    """退出"""
    request.session.flush()
    return redirect('web:home')

def account(request):
    """个人页"""
    head_form = HeadForm()
    password_form = PasswordForm(request)
    user = request.user
    account_form = AccountForm(request, instance=user)
    context = {'head_form': head_form, 'password_form': password_form, 'account_form': account_form}
    return render(request, 'web/account.html', context)

def headupdate(request):
    """更新头像"""
    if request.method == 'POST':
        # 取出文件后缀名,这里前端给我传的文件key为`文件`,大部分默认文件key为`file`
        fmt = str(request.FILES.get('head_portrait').name).split('.')[-1]
        # 设置文件名`用户特征信息`是我自己定义的变量,你可以在这里设置你需要传入的变量
        name = "{}.{}".format(request.user.username, fmt)
        # 修改文件名直接让文件.name等于新的文件名即可
        request.FILES.get('head_portrait').name = name
        img = request.FILES.get('head_portrait', '')

        id = request.user.id
        obj = models.UserInfo.objects.get(id=id)
        obj.head_portrait = img
        obj.save()
        return redirect('web:account')

def passwordupdate(request):
    """更新密码"""
    if request.method == 'POST':
        form = PasswordForm(request, data=request.POST)
        if form.is_valid():
            obj = models.UserInfo.objects.get(id=request.user.id)
            obj.password = form.cleaned_data['new_password']
            obj.save()

            return JsonResponse({'status': True})
        return JsonResponse({'status': False, 'error': form.errors})

def accountupdate(request):
    """更新密码"""
    if request.method == 'POST':
        form = AccountForm(request, data=request.POST)
        if form.is_valid():
            user = models.UserInfo.objects.get(id=request.user.id)
            user.username = form.cleaned_data['username']
            user.describe = form.cleaned_data['describe']
            user.save()

            return JsonResponse({'status': True})
        return JsonResponse({'status': False, 'error': form.errors})

def other(request, id):
    """他人个人页"""
    user = models.UserInfo.objects.get(id=id)
    context = {'user': user}
    obj = models.UserToUser.objects.filter(by_owner=int(id), user=request.user).first()

    if not obj:
        status = False
    else:
        status = obj.status
    context['status'] = status
    return render(request, 'web/other.html', context)

def concerned_user(request, id):
    """关注"""
    if request.method == 'POST':
        obj = models.UserToUser.objects.filter(by_owner=int(id), user=request.user).first()
        if obj:
            obj.status = True
            obj.save()
        else:
            usertouser = models.UserToUser()
            by_owner = models.UserInfo.objects.get(id=int(id))
            if by_owner == request.user:
                return JsonResponse({'status': 'False'})
            usertouser.user = request.user
            usertouser.by_owner = by_owner
            usertouser.save()

        return JsonResponse({'status': 'True'})

def unconcerned_user(request, id):
    """取消关注"""
    if request.method == 'POST':

        obj = models.UserToUser.objects.filter(by_owner=int(id), user=request.user).first()
        obj.status = False
        obj.save()
        return JsonResponse({'status': 'True'})

web/views/home.py
from django.shortcuts import render, redirect
from web.models import Forum, Topic
from web import models
from web.form.bbs import ForumForm
def home(request):
    """主页"""
    forums = Forum.objects.order_by('date_added')
    obj = Topic.objects.order_by('-floor_count')[:20]
    forum = models.UserToForum.objects.filter(user=request.user)
    user_forum = []
    for i in forum :
        user_forum.append(i.forum.id)
    usertouser = models.UserToUser.objects.filter(user=request.user)
    form = ForumForm()
    context = {'forums': forums, 'hottopic': obj, 'form': form, 'user_forum': user_forum}
    context['usertouser'] = usertouser
    return render(request, 'web/home.html', context)

web/templates/web/account.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}{{ request.user.username }}个人中心{% endblock %}

{% block css %}
<style>
  .personage {
    position: relative;
    right: 2px;
    border: 2px solid black;
    padding:10px 24px 10px 24px;
    width: 200px;
    float: left;
  }
  #box {
    position: relative;
    right: 2px;
    border: 2px solid black;
    padding:10px 24px 10px 24px;
    width: 200px;
    float: left;
  }
  .div1{}
  .div2{
    border: 2px solid black;
    padding:10px 24px 10px 24px;
    width: 200px;
    float: left;
    position: fixed;
    top:2%;
    left: 257px;
  }
  .forums{
    position: relative;
    left: 2px;
    border: 2px solid black;
    padding: 10px 10px 10px 10px;
    width: 800px;
    float: left;
  }
  .logo{
    width: 150px;
    height: 150px;
    }
  img.logo1{
    width: 150px;
    height: 150px;
    border-style: solid;
    border-color: black;
    border-width: 4px;
  } 
  .divforums{
  display: none;
  width: 800px;
  padding-right: 20px;
  float: left;
}
.forumimg{
  display: inline-block;
  width: 154px;
  height: 154px;
}
.forumimg:hover{
  border: 2px solid black;
}
.hottopic{
  border-bottom: 1px solid #ddd;
  padding-left: 20px;
  padding-right: 20px;
}

.hottopic:hover{
  background-color: rgb(240,240,240);
}
.hottopic a{
  color: rgb(52,92,161);
  font-size: 20px;
  font-weight: 600;
  line-height: 180%;
}
.hottopic a:hover{
  color: red;
}
.hottopic p{
  color: rgb(136,136,136);
  font-size: 15px;
  font-weight: 400;
  line-height: 200%;
}
.hottopic p a{
  color: rgb(136,136,136);
  font-size: 15px;
  font-weight: 400;
  line-height: 200%;
}
</style>
{% endblock %}

{% block content %}
<div class="content">
  <div id="box">
    <div id="float" class="div1">
      <div class='logo'>
        {% if request.user.head_portrait %}
        <img class='logo1' src='{{ request.user.head_portrait.url }}'>
        {% else %}
        <img class='logo1' src="{% static 'img/default.jpg' %}">
        {% endif %}
      </div>
      
      <h1>{{ request.user.username }}</h1>
      <h5>个性签名：</h5>
      {% if request.user.describe %}
      <p style="width: 150px;">{{ request.user.describe }}</p>
      {% else %}
      <p>这个人很懒什么也没留下</p>
      {% endif %}
      <div><a href="javascript:void(0)" onclick="switchtag('headupdate')">修改头像</a></div>
      <div><a href="javascript:void(0)" onclick="switchtag('passwordupdate')">修改密码</a></div>
      <div style="margin-bottom: 10px;"><a href="javascript:void(0)" onclick="switchtag('accountupdate')">修改资料</a></div>
      <ul class="nav nav-pills nav-stacked">
        <li id="li_cforum" role="presentation" class="active"><a href="javascript:void(0)" onclick="switchtag('cforum')">版块中心</a></li>
        <li id="li_ctopic" role="presentation"><a href="javascript:void(0)" onclick="switchtag('ctopic')">收藏的帖子</a></li>
        <li id="li_stopic" role="presentation"><a href="javascript:void(0)" onclick="switchtag('stopic')">发出的帖子</a></li>
        <li id="li_floor" role="presentation"><a href="javascript:void(0)" onclick="switchtag('floor')">发出的回复</a></li>
      </ul>
    </div>
  </div>
  <div class="forums">
    <div class="divforums" id="cforum" style="display: block;">
      <div style="width: 800px;">
      {% if request.user.power == 2 %}
        <h2>管理的版块</h2>
        {% for forum in request.user.forum_set.all %}
        <div style="margin: 4px 20px 4px 20px;">
          <a href="{% url 'web:forum' forum.id%}" class="forumimg">
            <img style="height: 150px; width: 150px;" src='{{ forum.picture.url }}'>
          </a>
          <div>
            <a href="{% url 'web:forum' forum.id %}">{{ forum }}</a>
          </div>
        </div>
        {% endfor %}
      {% endif %}
      </div>
      <div style="width: 800px;">
        <h2>关注的版块</h2>
        {% for concerned in request.user.usertoforum_set.all %}
        {% if concerned.status == 1 %}
        <div style="float: left;margin: 4px 20px 4px 20px;">
        <a href="{% url 'web:forum' concerned.forum.id%}" class="forumimg">
          <img style="height: 150px; width: 150px;" src='{{ concerned.forum.picture.url }}'>
        </a>
        <div id='concerned_{{ concerned.forum.id }}'>
          <a  style="float: right;" href="javascript:unConcerned({{ concerned.forum.id }});">取消关注</a>
          <a  href="{% url 'web:forum' concerned.forum.id %}">{{ concerned.forum }}</a>
        </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
    </div>
    <div class="divforums" id="headupdate">
      <h2>修改头像</h2>
      <form action="{% url 'web:headupdate' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in head_form %}
          <div class="form-group">
            {{ field }}
            <span class="error-msg">{{ field.errors.0 }}</span>
          </div>
        {% endfor %}
        <input type="submit" value="提交">
      </form>
    </div>
    <div class="divforums" id="passwordupdate">
      <div style="width: 400px;">
        <h2>修改密码</h2>
        <form id="passwordform" action="{% url 'web:passwordupdate' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in password_form %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field }}
              <span class="error-msg">{{ field.errors.0 }}</span>
            </div>
          {% endfor %}
          <input id="btnSubmit" type="button" class="btn btn-primary" value='提交'>
        </form>
      </div>
    </div>
    <div class="divforums" id="accountupdate">
      <div style="width: 400px;margin-left: 180px;">
        <h2>修改资料</h2>
        <form id="accountform" action="{% url 'web:passwordupdate' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in account_form %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field }}
              <span class="error-msg">{{ field.errors.0 }}</span>
            </div>
          {% endfor %}
          <input id="accountSubmit" type="button" class="btn btn-primary" value='提交'>
        </form>
      </div>
    </div>
    <div class="divforums" id="ctopic">
      <h2>收藏的帖子</h2>
      {% for collect in request.user.collect_set.all %}
      {% if collect.status == 1 %}
      <li>
        <div class="hottopic">
          <a href="{% url 'web:topic' collect.topic.id %}">{{ collect.topic }}</a>
          <div class="content_img">{{ collect.topic.floor_set.first|safe }}</div>
          <p id='collect_{{ collect.topic.id }}' style="float: right;">
            <a  href="javascript:unCollect({{ collect.topic.id }});">取消收藏</a>
          </p>
          <p>
            <i class="fa fa-user"></i> 
            <a href="{% url 'web:other' collect.topic.floor_set.first.owner.id%}">{{ collect.topic.floor_set.first.owner }}</a> / 
            <a href="{% url 'web:forum' collect.topic.forum.id%}">{{ collect.topic.forum }}</a>
          </p> 
        </div>
      </li>
      
      {% endif %}
      {% endfor %}
    </div>
    <div class="divforums" id="stopic">
      <h2>发起的帖子</h2>
      {% for topic in request.user.topic_set.all %}
      <li>
        <div class="hottopic">
          <a href="{% url 'web:topic' topic.id %}">{{ topic }}</a>
          <div class="content_img">{{ topic.floor_set.first|safe }}</div>
          <p id='topic_{{ topic.id }}' style="float: right;">
            <a href="javascript:topicDel({{ topic.id }});"> 删除</a>
          </p>
          <p>
            <i class="fa fa-user"></i> 
            <a href="{% url 'web:other' topic.floor_set.first.owner.id%}">{{ topic.floor_set.first.owner }}</a> / 
            <a href="{% url 'web:forum' topic.forum.id%}">{{ topic.forum }}</a>
          </p> 
        </div>
      </li>
      
      {% endfor %}
    </div>
    <div class="divforums" id="floor">
      <h2>发出的回复</h2>
      {% for floor in request.user.floor_set.all %}
      <li>
        <div class="hottopic">
          <a href="{% url 'web:topic' floor.topic.id %}">{{ floor.topic }}</a>
          <div class="content_img">{{ floor|safe }}</div>
          <p id='floor_{{ floor.id }}' style="float: right;">
            <a href="javascript:floorDel({{ floor.id }});"> 删除</a>
          </p>
          <p>
            <i class="fa fa-user"></i> 
            <a href="{% url 'web:other' floor.owner.id%}">{{ floor.owner }}</a> / 
            <a href="{% url 'web:forum' floor.topic.forum.id%}">{{ floor.topic.forum }}</a>
          </p> 
        </div>
      </li>
      {% endfor %}
    </div>
  </div>  
</div>
<div style="height: 110px;position: fixed;bottom:-30px;right: 10%;">
  <ul >
    <li >
      <div style="background-color: #337ab7;width: 50px;height: 50px;border-radius:4px;">
        <a href="javascript:void(0)" onclick="goto_top()">
          <i class="fa fa-chevron-up fa-2x" style="color: rgb(234,240,251);position: relative;left:11px ;top:10px"></i>
        </a>
      </div>
    </li>
  </ul>
</div>    
{% endblock %}

{% block js %}
    <script>
      $.ajaxSetup({
        data:{csrfmiddlewaretoken:'{{ csrf_token }}'}
      })
      function switchtag(a){
    $(".divforums").hide();
    $("#"+a).slideDown("slow");
    $('.active').removeClass("active");
    $('#li_'+a).addClass("active");
}
      $(document).ready(function() {
      var obj = $(".content_img").find("img").css({"max-height":"300px","width":"auto"});
  });
  (function(){   
    var oDiv=document.getElementById("float");   
    var H=0,iE6;   
    var Y=oDiv;   
    while(Y){H+=Y.offsetTop;Y=Y.offsetParent};   
    iE6=window.ActiveXObject&&!window.XMLHttpRequest;   
    if(!iE6){   
        window.onscroll=function()   
        {   
            var s=document.body.scrollTop||document.documentElement.scrollTop;   
            if(s>H){oDiv.className="div1 div2";if(iE6){oDiv.style.top=(s-H)+"px";}}   
            else{oDiv.className="div1";}       
        };   
    }   
})(); 
var goto_top_type = -1;  
var goto_top_itv = 0;  
  
function goto_top_timer() {  
    var y = goto_top_type == 1 ? document.documentElement.scrollTop  
            : document.body.scrollTop;  
    var moveby = 15;  
    y -= Math.ceil(y * moveby / 100);  
    if (y < 0) {  
        y = 0;  
    }  
    if (goto_top_type == 1) {  
        document.documentElement.scrollTop = y;  
    } else {  
        document.body.scrollTop = y;  
    }  
    if (y == 0) {  
        clearInterval(goto_top_itv);  
        goto_top_itv = 0;  
    }  
}  
  
function goto_top() {  
    if (goto_top_itv == 0) {  
        if (document.documentElement && document.documentElement.scrollTop) {  
            goto_top_type = 1;  
        } else if (document.body && document.body.scrollTop) {  
            goto_top_type = 2;  
        } else {  
            goto_top_type = 0;  
        }  
        if (goto_top_type > 0) {  
            goto_top_itv = setInterval('goto_top_timer()', 50);  
        }  
    }  
} 
    $('#btnSubmit').click(function (){
        $('.error-msg').empty();
        $.ajax({
            url:"{% url 'web:passwordupdate' %}",
            type:"POST",
            data:$('#passwordform').serialize(),
            dataType:"JSON",
            success:function (res) {
                if(res.status){
                    location.href = location.href;
                }else{
                    $.each(res.error, function(key, value){
                        $("#id_" +key).next().text(value[0]);
                    })
                }
            }
        })
    })
    $('#accountSubmit').click(function (){
        $('.error-msg').empty();
        $.ajax({
            url:"{% url 'web:accountupdate' %}",
            type:"POST",
            data:$('#accountform').serialize(),
            dataType:"JSON",
            success:function (res) {
                if(res.status){
                    location.href = location.href;
                }else{
                    $.each(res.error, function(key, value){
                        $("#id_" +key).next().text(value[0]);
                    })
                }
            }
        })
    })
    </script>
    <script src="{% static 'js/account.js' %}"></script>
{% endblock %}

web/templates/web/change_power.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}修改权限{% endblock %}
{% block css %}
    
{% endblock %}

{% block content %}
    {% if request.user.power == 4 %}
    <h1>修改版主</h1>
    {% elif request.user.power == 3 %}
    <h1>修改版务</h1>
    {% endif %}
      <select id="lcomuli" class="form-control">
        {% for forum in forums %}
        <option value={{ forum.id }}>{{ forum }}</option>
        {% endfor %}
      </select>
    {% if request.user.power == 4 %}
      <button type="button" onclick="moderator({{ user.id }})">修改</button>
    {% elif request.user.power == 3 %}
      <button type="button" onclick="Submit({{ user.id }})">修改</button>
    {% endif %}
{% endblock %}

{% block js %}
    <script>
        $.ajaxSetup({
          data:{csrfmiddlewaretoken:'{{ csrf_token }}'}
        })
    </script>
    <script src="{% static 'js/change_power.js' %}"></script>
{% endblock %}

web/templates/web/headupload.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}首页{% endblock %}
{% block css %}
    
{% endblock %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="提交">
  </form>
{% endblock %}

{% block js %}

{% endblock %}

web/templates/web/login.html
{% extends 'layout/basic.html' %}

{% block title %}用户登录{% endblock %}

{% block css %}

{% endblock %}

{% block content %}
<h1 style="text-align:center;">用户登录</h1>
<div class="account">
  <form  method="POST" novalidate>
    {% csrf_token %}
    {% for field in form %}
    {% if field.name == 'code' %}
    <div class="form-group">
      <label for="{{field.id_for_label}}">{{field.label}}</label>
      <div class="clearfix">
        <div class="col-md-6" style="padding-left:0">
          {{field}}
          <span class="error-msg" style="font-size: 12px;">{{ field.errors.0 }}</span>
        </div>
        <div class="col-md-6">
          <img src="{% url 'web:image_code' %}" id="imageCode" title="点击更换图片">
        </div>
      </div>
    </div>
    {% else %}
    <div class="form-group">
      <label for="{{field.id_for_label}}">{{field.label}}</label>
      {{field}}
      <span class="error-msg" style="font-size: 12px;">{{ field.errors.0 }}</span>
    </div>
    {% endif %}
    {% endfor %}
    <div>
      <div style="float:right ;">
        <a href="{% url 'web:login_sms' %}">手机验证码登录</a>
      </div>
    </div>
    <input type="submit" class="btn btn-primary" value='登录'>
  </form>
</div>

{% endblock %}

{% block js %}
    <script>
        $(function (){
            $('#imageCode').click(function (){
                var oldSrc = $(this).attr('src');
                $(this).attr('src', oldSrc + "?");
            })
        })
    </script>
{% endblock%}